# Generated by Django 5.1.7 on 2025-03-23 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('RUNNING', 'Running'), ('CYCLING', 'Cycling'), ('WEIGHTLIFTING', 'Weightlifting'), ('SWIMMING', 'Swimming')], max_length=50)),
                ('duration', models.PositiveIntegerField()),
                ('distance', models.FloatField()),
                ('calories_burned', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
